[package]
name = "draw"
version = "0.1.0"
authors = ["silas"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libary = { path = "../lib" }
piston_window = "0.112.0"
